### ISSUE TITLE
Create sample for Exeter

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/decision-letter-parser#22]
## Problem / Motivation

- WHO: Exeter
- WHEN and WHERE: As soon as it's ready to be sent to them via email is fine
- WHAT: They want a sample set of files they would receive when we start producing the decision letters and author responses inhouse and sending them the XML and named files
- WHY: So they can quote for the work to develop this workflow on their side

## Proposed solution
Graham to send them a sample once he's close to the final solution

## Clarification needed and assumptions

---

## User interface / Wireframes
NA

**Comment by gnott** [comment]
Related to this, I will draft enhancements to the `00666` article kitchen sink XML (https://github.com/elifesciences/XML-mapping/blob/master/elife-00666.xml) where the decision letter and author response includes more of the possible content that may appear in those sub-articles.

The sample for the decision letter API will be slightly different: it will have a different root XML tag, and the `@id` attributes of some tags may be different, since the numbering will start at `1` when producing just the decision letter XML alone.

**Comment by gnott** [comment]
Provisional XML sample is currently on the `kitchen-sink` branch at https://github.com/elifesciences/decision-letter-parser/blob/kitchen-sink/tests/fixtures/kitchen_sink.xml  When we are happy, we can merge it into the `develop` branch.

I assume the sample package does not need to include  TIFF and MP4 video file. Plans are those will be sent by FTP.

**Comment by gnott** [comment]
For reference, the kitchen sink XML at this point is like the one in the test fixtures except it has XML tags on new lines but no indenting of the tags so as to not introduce additional whitespace. I will attach the sample here for reference in future if we want to look back at it (with a `.txt` extension to allow me to attach it here).

[kitchen_sink.xml.txt](https://github.com/elifesciences/decision-letter-parser/files/3660032/kitchen_sink.xml.txt)
